### ISSUE TITLE
Notebook Review

### ISSUE THREAD

**Issue by adelnehme** [datacamp/Hacker-Stats-in-Python-Live-Training#1]
Hi @justinbois :wave:

This is an awesome notebook you have there - it's really impressive given the short turn around and I have very minimal feedback. I also definitely agree with the notion of splitting up the content and abridging this session's length. Here's my review for part I:

### General Feedback

- [x] 🔧 **A.** I see that there are a lot of different written instances in the notebooks that connect back to the statistical thinking courses. Feel free to plug in your courses as much as you see fit verbally - however for the sake of keeping the notebook more concise and dedicating markdown space for explaining concepts only, I recommend adding images of the course badge with links in the Statistical Inference section below similar to how it's done in this [notebook on time-series analysis](https://colab.research.google.com/github/datacamp/time-series-analysis-in-python-live-training/blob/master/notebooks/Time_Series_Analysis_in_Python_solution.ipynb) with a bit of text explaining how the content of this session is largely based on these 2 courses and that they have much more to teach. Given that, I recommend discarding all other instances of markdown that directly mention the statistical thinking courses.

![image](https://user-images.githubusercontent.com/48436758/86229839-9227fb80-bb90-11ea-86c4-7287fda46e00.png)

- [x] 🔧 **B.** Consider adding 4 Q&A sessions throughout the entire notebook by using the below in a markdown cell. I definitely think there should be a Q&A session after the statistical inference section just before we introduce the dataset - I'll let you space out the remaining Q&A sessions given you have much more intimate knowledge on teaching these topics live and what often gives cognitive overload when doing it.

```
---
<center><h1> Q&A 1</h1> </center>
---
```

### Introductory cell

- [x] 🔧 **1.** To set expectations better - I recommend not writing explicitly that there is a part II for this session on markdown - but simply verbalizing during the session that there we could explore more topics down the line. The reason behind this is simply not to give students the impression that there is a part II they can sign up to right now. 

### Statistical Inference

:star: I think it's excellent how you decide to dedicate the early portion of the session to conceptually going over the concepts used in the session. 

### Automating and organizing confidence intervals

- [x] 🔧 **2.** Would it be possible to have a function here instead of a class definition? I anticipate many students may not have OOP knowledge here to truly dissect `ConfInt1D()` and follow along what's being done without cognitive overload.

### Visualizing Confidence Intervals

- [x] 🔧 **3.** I recommend a small note just explaining how matplotlib subplots work since they are often a source of confusion. Check out the gif used [here](https://colab.research.google.com/github/datacamp/machine-learning-with-scikit-learn-live-training/blob/master/notebooks/Machine%20learning%20with%20scikit%20learn_solution.ipynb) in the **Exploratory Analysis for Machine Learning** section. It's nothing too in-depth, really just a 5-minute reminder that this is how matplotlib works in the background and that as long as we understand this the specific syntax is not as important as getting the intuition - feel free to plug in a data visualization course from DataCamp if you think it fits better.

**Comment by adelnehme** [comment]
- [x] Action Item:  Fill out Marketing Form for [Part 2](https://docs.google.com/forms/d/e/1FAIpQLSeLZ3IeiRdvvtZD15DWVnr-rNO-bOuwDj_2QhUg5jYBE40Qag/viewform)

- [ ] Action Item: Agree with Kelsey on date of second session

- [x] Action Item: Share with Kelsey updated name for this [session](https://www.datacamp.com/live/hacker-stats-in-python) and what will I learn?

**Comment by justinbois** [comment]
Re: Matplotlib axes for visualizing confidence intervals: I didn't want to dwell on it too long, but rather explicitly said for ease of this live training, they can think of the plotting function as a black box. I very briefly describe the object-oriented flavor of Matplotlib we're using here.

**Comment by justinbois** [comment]
I updated the notebook to work without the class definition. It is stored in `notebooks/hacker_stats_in_python_part_1_without_ConfInt_class_solution.ipynb`.

For *this* notebook, it makes sense to do it without the ConfInt class, but there are two reasons I would like to keep it in.

1. It is good style to keep it, and does help keep the information organized. It also cements in the students mind that these things are all related and follow directly from having a data set consisting of repeated measurements. I did add some more discussion to the notebook about why we're using a class and how we do it.
2. Having this class keeps things *much* better organized in the part II. When we start looking at correlations and confidence intervals thereof, there are four combinations, and keeping track of everything gets more difficult without a class.

In light, I do think  class will be very useful in part II of the training. We could perhaps introduce the class in *that* training as opposed to this one, which I am totally fine with. Just let me know what you prefer.

**Comment by adelnehme** [comment]
Hi @justinbois :wave:

Thanks for getting to the feedback and for creating the student ready notebooks -- they look fantastic! For keeping the `confint` class - I think one thing we can do is keep it in the second session with a small piece of markdown reminding students of what this class tries to organize from session 1? What do you think?

**Comment by justinbois** [comment]
Do you mean that we use keep it only in the second lesson, but not in the first? If so, I'm fine with that.

**Comment by adelnehme** [comment]
Yep ^^ -- Thanks.

**Comment by justinbois** [comment]
Ok. I will close this issue when I have appropriately updated the second notebook.
