### ISSUE TITLE
Justin <> Justin

### ISSUE THREAD

**Issue by adelnehme** [datacamp/Hacker-Stats-in-Python-Live-Training#2]
Hi @justinbois :wave:

At DataCamp, we find it important that all live trainings receive the time they deserve. Since next week I will be largely unavailable due to travel plans - we think it’s best to move your live training over to another Content team member for the remainder of its development.

Through this GitHub issue, I want to introduce you to @jsaddlemyer, one of our best Content Quality Analysts, who will be taking over from me. Given that the notebook for the second session is almost ready for review, I suggest just letting Justin know immediately when the notebook for part II is ready for review and propose scheduling a call with him for next week to go over the content and the notebook together. You can schedule this call by using his calendly link [here](https://calendly.com/justinsaddlemyer/30min) and sign up for a 30-minute time slot.

From that point, Justin will be your main point of contact for Content and @KelseyMcNeillie for anything logistics-related for the session. The content creation process moving forward doesn’t change. I was really looking forward to working on part II with you :smile: But I’m happy Justin will see what a cool gig it is to develop content with you!

Cheers,
Adel

**Comment by justinbois** [comment]
Thanks, Adel! @jsaddlemyer , I'll let you know as soon as I have the second notebook ready for review. Probably some time over the weekend.

Thanks for your help, @adelnehme !

**Comment by jsaddlemyer** [comment]
Hi @justinbois,

Great to hear, and look forward to seeing it!

Kind regards and have a great weekend!

Justin
