### ISSUE TITLE
Part 2 Review

### ISSUE THREAD

**Issue by jsaddlemyer** [datacamp/Hacker-Stats-in-Python-Live-Training#3]
Hi Justin,

First off, great work. I really wish I had something similar when I first learned stats. Structurally I think it has a nice flow, a good overview of the previous section, and the concepts are well explained. Below are my only comments.

Edits/suggestions (suggested adaptation in bold):

- **The Dataset** section: 
    - [x] In this study, subjects also took surveys to determine properties about their sleep. The surveys provide three different **metrics** of sleep quality and wakefulness. 
- **Loading in the data set** section: 
    - [x] confidence when incorrect: Average confidence when the subject gave **an incorrect** response for all trials
- **Effect of sleep quality on performance** section: 
    - [x] We have just investigated how the different sleep metrics are correlated. Now, **let's** turn our attention…
    - [x] Is the equation for the Pearson correlation correct? I could be mistaken, but shouldn’t the variances of x and y be represented as the variance of x is represented in the equation for the slope of the linear regression?
- **Performing a linear regression** section: 
    - [x] The intercept is given by the mean of the y-values minus the slope **times** the mean of the x-values.
    - [x] I pause to **note** here that the slope (which is of primary interest) and the intercept are numbers
- **A NHST for a linear regression** section:
    - [x] If I re-run the notebook, I get a different p-value than what is currently remaining as output in the notebook.

**Comment by justinbois** [comment]
Thanks for the kind work, @jsaddlemyer . A few points:

1. The Pearson correlation formula is correct as written.
2. Great catch on the NHST. Fixed.
3. @adelnehme suggested not defining classes, as not all learners will be familiar with it. I wasn't sure how to do it, so I left the classes in there. I ended up coming up with a clean way to do it without classes using dictionaries and a function, so I updated the notebook to that effect.

I'll generate the student notebook soon.

**Comment by jsaddlemyer** [comment]
Hi @justinbois,

1) My apologies, I think I misread the description below regarding the equation. 
3) I think the way you had introduced and described classes in the notebook was already clear, even to students not totally familiar with them. But indeed, the dictionary/function approach is a great alternative and should make it more accessible to students.

Thanks again!

Justin
